---
title: "summary"
author: "Evan Odell"
date: "27 January 2017"
output: html_document
---

## Using this map

This map contains information on the location and contact information for every charity registered with the Charity Commission that include amateur sport and recreation, disability and disabled people, or both, in their area of focus. By default, the map shows all charities in England that list both sports/recreation and disability/disabled people as an area of focus. 

The map and the table update each other. So if you zoom in on the map, the table will only contain charities that are on the map. If you search in the table, only charities that meet what you are searching for will be displayed on the map.

The penguin icons, which you can turn on and off with the 'Show Get Yourself Active Partners' checkbox, indicate partners in the [Get Yourself Active](http://www.getyourselfactive.org/) programme. The 'Show Primary Charities Only' checkbox hides subsidary charities, and only shows the primary charity that is registered with the Charity Commission.

To search by the name of a charity or area use the search box in the table beneath the map.

To see more columns, click on the 'Column Visibility' button on the upper left side of the table.

To reset the map, click on the 'Reset Search' button on the right side of the page.

Previous versions of this app had the function to filter charities by income, but this was removed in an attempt to speed up processing times. If you would like this restored, would like to see any other features, or want to have similar maps with other information, please contact [Evan Odell](mailto:evan.odell@disabilityrightsuk.org).

### Download Information

To download information from this map in a CSV file format, which can be opened in Excel or other spreadsheet programmes, click the 'Download CSV File' button on the right-hand side of the app. The spreadsheet will contain all charities that are contained in the table at the moment you click the button, even if they are not on the front page of the table. You can also download this data as a TSV file if you prefer, which can also be opened in Excel.

### Assistance

If you have any suggestions, questions or comments, please contact [Evan Odell](mailto:evan.odell@disabilityrightsuk.org) or [Leanne Wightman](mailto:leanne.wightman@disabilityrightsuk.org).

#### Data and Licensing

Source code is available on [Github](https://github.com/EvanOdell/dis-sport).

This app is licensed under an [MIT License](https://github.com/EvanOdell/dis-sport/blob/master/licence). Charity data is taken from the [Charity Commission data download](http://data.charitycommission.gov.uk/), and is licensed under the Open Government Licence v3.0. This data is accurate as of the February 2017 Charity Commission Bulk Data release, and includes all charities that include amateur sport and recreation, disability and disabled people, or both, in their area of focus, and have financial filings dated on or after 2015-06-01.


