---
title: "summary"
author: "Evan Odell"
date: "27 January 2017"
output: html_document
---

## Using this directory

To search by the name of a charity or area use the search box in the table beneath the map.

To see more columns, click on the 'Column Visibility' button on the upper left side of the table.

### Download Information

To download information from this map in a CSV file format, which can be opened in Excel or other spreadsheet programmes, click the 'Download CSV File' button on the right-hand side of the app. The spreadsheet will contain all charities that are contained in the table at the moment you click the button, even if they are not on the front page of the table.

### Assistance

If you have any suggestions, questions or comments, please contact [Evan Odell](mailto:evan.odell@disabilityrightsuk.org) or [Leanne Wightman](mailto:leanne.wightman@disabilityrightsuk.org).

#### Data and Licensing

Source code is available on [Github](https://github.com/EvanOdell/dis-sport).

This app is licensed under an [MIT License](https://github.com/EvanOdell/dis-sport/blob/master/licence). Charity data is taken from the [Charity Commission data download](http://data.charitycommission.gov.uk/), and is licensed under the Open Government Licence v3.0. This data is accurate as of the September 2017 Charity Commission Bulk Data release, and includes all charities that include amateur sport and recreation, disability and disabled people, or both, in their area of focus, and have updated their charity commission accounts within the last 18 months.


